// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: wal_message/v1/wal.proto

package wal_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalSerialization int32

const (
	WalSerialization_WAL_SERIALIZATION_UNSPECIFIED WalSerialization = 0
	WalSerialization_WAL_SERIALIZATION_PROTO       WalSerialization = 1
	WalSerialization_WAL_SERIALIZATION_JSON        WalSerialization = 2
)

// Enum value maps for WalSerialization.
var (
	WalSerialization_name = map[int32]string{
		0: "WAL_SERIALIZATION_UNSPECIFIED",
		1: "WAL_SERIALIZATION_PROTO",
		2: "WAL_SERIALIZATION_JSON",
	}
	WalSerialization_value = map[string]int32{
		"WAL_SERIALIZATION_UNSPECIFIED": 0,
		"WAL_SERIALIZATION_PROTO":       1,
		"WAL_SERIALIZATION_JSON":        2,
	}
)

func (x WalSerialization) Enum() *WalSerialization {
	p := new(WalSerialization)
	*p = x
	return p
}

func (x WalSerialization) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalSerialization) Descriptor() protoreflect.EnumDescriptor {
	return file_wal_message_v1_wal_proto_enumTypes[0].Descriptor()
}

func (WalSerialization) Type() protoreflect.EnumType {
	return &file_wal_message_v1_wal_proto_enumTypes[0]
}

func (x WalSerialization) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalSerialization.Descriptor instead.
func (WalSerialization) EnumDescriptor() ([]byte, []int) {
	return file_wal_message_v1_wal_proto_rawDescGZIP(), []int{0}
}

type CounterUint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         uint64                 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterUint) Reset() {
	*x = CounterUint{}
	mi := &file_wal_message_v1_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterUint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterUint) ProtoMessage() {}

func (x *CounterUint) ProtoReflect() protoreflect.Message {
	mi := &file_wal_message_v1_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterUint.ProtoReflect.Descriptor instead.
func (*CounterUint) Descriptor() ([]byte, []int) {
	return file_wal_message_v1_wal_proto_rawDescGZIP(), []int{0}
}

func (x *CounterUint) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CounterUint) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_wal_message_v1_wal_proto protoreflect.FileDescriptor

const file_wal_message_v1_wal_proto_rawDesc = "" +
	"\n" +
	"\x18wal_message/v1/wal.proto\x12\x0ewal_message.v1\"5\n" +
	"\vCounterUint\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value*n\n" +
	"\x10WalSerialization\x12!\n" +
	"\x1dWAL_SERIALIZATION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WAL_SERIALIZATION_PROTO\x10\x01\x12\x1a\n" +
	"\x16WAL_SERIALIZATION_JSON\x10\x02B\xbe\x01\n" +
	"\x12com.wal_message.v1B\bWalProtoP\x01ZIgithub.com/wargasipil/stream_engine/proto_core/wal_message/v1;wal_message\xa2\x02\x03WXX\xaa\x02\rWalMessage.V1\xca\x02\rWalMessage\\V1\xe2\x02\x19WalMessage\\V1\\GPBMetadata\xea\x02\x0eWalMessage::V1b\x06proto3"

var (
	file_wal_message_v1_wal_proto_rawDescOnce sync.Once
	file_wal_message_v1_wal_proto_rawDescData []byte
)

func file_wal_message_v1_wal_proto_rawDescGZIP() []byte {
	file_wal_message_v1_wal_proto_rawDescOnce.Do(func() {
		file_wal_message_v1_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wal_message_v1_wal_proto_rawDesc), len(file_wal_message_v1_wal_proto_rawDesc)))
	})
	return file_wal_message_v1_wal_proto_rawDescData
}

var file_wal_message_v1_wal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wal_message_v1_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wal_message_v1_wal_proto_goTypes = []any{
	(WalSerialization)(0), // 0: wal_message.v1.WalSerialization
	(*CounterUint)(nil),   // 1: wal_message.v1.CounterUint
}
var file_wal_message_v1_wal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wal_message_v1_wal_proto_init() }
func file_wal_message_v1_wal_proto_init() {
	if File_wal_message_v1_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wal_message_v1_wal_proto_rawDesc), len(file_wal_message_v1_wal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wal_message_v1_wal_proto_goTypes,
		DependencyIndexes: file_wal_message_v1_wal_proto_depIdxs,
		EnumInfos:         file_wal_message_v1_wal_proto_enumTypes,
		MessageInfos:      file_wal_message_v1_wal_proto_msgTypes,
	}.Build()
	File_wal_message_v1_wal_proto = out.File
	file_wal_message_v1_wal_proto_goTypes = nil
	file_wal_message_v1_wal_proto_depIdxs = nil
}
